apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: worktracker
  namespace: worktracker
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: worktracker.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: worktracker-api
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: worktracker-web
                port:
                  number: 80