apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: worktracker
  namespace: worktracker
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - krystian-sitarz.pl
        - www.krystian-sitarz.pl
      secretName: worktracker-tls
  rules:
    - host: krystian-sitarz.pl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: worktracker-web
                port:
                  number: 80
    - host: www.krystian-sitarz.pl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: worktracker-web
                port:
                  number: 80
